spring.application.name=api_productos

# Configuración de base de datos H2 en memoria
   spring.datasource.url=jdbc:mysql://localhost:3306/inventariodb
   spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
   spring.datasource.username=root
   spring.datasource.password=${DB_PASSWORD}

# Configuración de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
